export const ACTIONS = {
  GET_USER_DATA: "GET_USER_DATA",
  SIDE_BAR_STATE: "SIDE_BAR_STATE",
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  GET_ALL_POSTS: "GET_ALL_POSTS",
  DELETE_POST_RESPONSE: "DELETE_POST_RESPONSE",
  UPDATE_POST_RESPONSE: "UPDATE_POST_RESPONSE",
  CREATE_POST_RESPONSE: "CREATE_POST_RESPONSE",
};
